FROM public.ecr.aws/docker/library/python:3.10
ENV FLASK_RUN_HOST=0.0.0.0

WORKDIR /

RUN adduser --uid 1000 --disabled-password --gecos "" app

RUN apt-get update && \
  apt-get install -y \
  pcre2-utils \
  gcc \
  build-essential \
  libpcre2-dev \
  libffi-dev \
  && pip install pipenv

RUN mkdir -p /var/www/app && mkdir /app

COPY Pipfile Pipfile.lock /app/
RUN cd /app && pipenv install --system --deploy

COPY . /app

CMD uwsgi --http :5000 --master --enable-threads -s /var/www/app/app.sock --manage-script-name --mount /=app:app